<?php
namespace app\api\controller;
use lib\QinqiuPpi;
use lib\Easemob;
use think\Controller;
use think\View;
use think\Db;
use opensearch;
use \think\Session;
use \think\Request;

class Live extends Common{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @param lag
     * @param log
     * @param t
     * @开启直播
     */
    public function start_live(){
//        $qn = new QinqiuPpi();
//        $qn->hub();exit;
        $param = Request::instance()->request();
        $log = empty($param["log"]) ? '': $param["log"];
        $lag = empty($param["lag"]) ? '': $param["lag"];
        $lag = empty($param["title"]) ? '': $param["title"];
        if($log && $lag){
            $gwd = $lag.','.$log;
            $baidu_apikey = DB::name('System')->value('baidu_apikey');
            $file_contents = file_get_contents('http://api.map.baidu.com/geocoder/v2/?ak='.$baidu_apikey.'&location='.$gwd.'&output=json');
            $rs = json_decode($file_contents,true);
            $sheng = $rs['result']['addressComponent']['province'];
            $shi = $rs['result']['addressComponent']['city'];
            $qu = $rs['result']['addressComponent']['district'];
            $address = $rs['result']['formatted_address'];
        }
        $user = DB::name('member')->where(['member_id' =>'519'])->find();
        $user['member_nick_name'] ? $name = $user['member_nick_name'] : $name = "直播间" . rand(100, 999);
        $options = [
            'name' => $name,
            'description' => $name,
            'maxusers' => 3000,
            'owner' => $user['hx_username']
        ];
        $hx = new Easemob();
        $create = $hx->createChatRoom($options);
        (!empty($create['error'])) ? error('创建聊天室失败!') : true;
        $qn = new QinqiuPpi();
        $play_address = $qn->hub(); //七牛
        $qiniu_room_id = time().rand(100, 999);
        $qiniu_room_name = "主播".rand(10000,99999);
        $create_room =  createChatRoom($qiniu_room_id,$qiniu_room_name);    //七牛创建房间
        $time = time();
//        $data = [
//            'user_id'=>$u['member_id'],
//            'play_img'=>$img,
//            'title'=>$title,
//            'lebel'=>$lebel,
//            'push_flow_address'=>$play_address['url'],
//            'play_address'=>$play_address['url2'],
//            'play_address_m3u8'=>$play_address['m3u8'],
//            'start_time'=>$time,
//            'stream_key'=>$play_address['streamKey'],
//            'live_status'=>1,
//            'live_time'=>0,
//            'room_id'=>$create['data']['id'],
//            'intime'=>$time,
//            'date'=>date('Y-m-d',$time),
//            'log'=>$log,
//            'lag'=>$lag,
//            'sheng'=>$sheng,
//            'shi'=>$shi,
//            'qu'=>$qu,
//            'address'=>$address,
//            'qiniu_room_id'=>$create_room['room_id'],
//            'qiniu_room_name'=>$create_room['room_name'],
//            'qiniu_token'=>$create_room['token'],
//            "livewindow_type"  => 1,
//        ];
//        M("live")->where(["user_id" => $u["member_id"]])->save(["live_status"=>2]);



    }
}