<?php
namespace app\api\controller;
use lib\Easemob;
use think\Controller;
use think\View;
use think\Db;
use opensearch;
use \think\Session;
use \think\Request;

class Login extends Common
{
    private $cdkey = "8SDK-EMY-6699-RHRPN";
    private $password = "647039";
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 发送验证码
     */
    public function sendSMS($mobile="18222169593"){
        $mobile = Request::instance()->request('mobile');
        if (empty($mobile) || !preg_match('#^13[\d]{9}$|14^[0-9]\d{8}|^15[0-9]\d{8}$|^18[0-9]\d{8}|^17[0-9]\d{8}$#', $mobile)) {
            error("手机格式不正确");
        }else{
            //一分钟只能发送一条
            $intime = DB::name("Mobile_sms")->field(["intime"])->where(["mobile"=>$mobile])->order('intime desc')->find();;
            $mistiming = time()-intval($intime["intime"]);
            if($mistiming<60){
                error("一分钟只能发送一条短信");
            }
            //每天只能发送10条
            $send_count = DB::name("mobile_sms")->where(["mobile"=>$mobile,"date"=>date("Y-m-d")])->count();
            if($send_count>10) {
                error("今天短信发送数量已达上限");
            }
            $system = DB::name('system')->field('tengxun_appid,tengxun_appkey,code_volidity')->where(['id'=>1])->find();
            $date = DB::name("user")->where(array('phone'=>$mobile))->find();
            $mobile_code = random(6, 1);
            $content = "【龙脉直播】您的验证码为".$mobile_code.",如非本人操作请忽略此消息。";
        }
        $url='http://hprpt2.eucp.b2m.cn:8080/sdkproxy/sendsms.action?cdkey='.$this->cdkey.'&password='.$this->password.'&phone='.$mobile.'&message='.$content;
        file_get_contents($url);
        DB::name('Mobile_sms')->insert(['mobile'=>$mobile,'code'=>$mobile_code,'state'=>1,'date'=>date('Y-m-d',time()),'intime'=>time()]);
        success('发送成功!');
        }
    /**
     * 注册和登录
     */
    public function message_login(){
        $param = Request::instance()->request();
        $log = empty($param["log"]) ? '': $param["log"];
        $lag = empty($param["lag"]) ? '': $param["lag"];
        if(empty($param["mobile"]) || !(preg_match("/^1[34578]{1}\d{9}$/",$param["mobile"])) || empty($param["yzm"])){
            error("验证不正确");
        }
        $mobile = $param["mobile"];
        //判断验证码是否有效期
        $result = DB::name("Mobile_sms")->where(["mobile"=>$mobile,"code"=>$param["yzm"]])->order("intime desc")->find();
        if(!$result){
            error("验证码不正确");
        }
        $state = $result["state"];
        $valid_time =time()-intval($result["intime"]);
        if($valid_time>600 || $state==2){
            error("验证码已失效,请重新发送");
        }
        $user = DB::name("member")->where(["member_phone"=>$mobile])->find();
        if($user){
            //用户存在的时候
            if($user['is_del']==2){
                error('账号被限制,请联系平台!');
            }else{
                $member_token = uniqid();
                $user["token"] = $member_token;
                $user["img"] = $user["member_head_image"];
                DB::name("member")->where(["member_id"=>$user["member_id"]])->update(["member_token"=>$member_token]);
                DB::name("mobile_sms")->where(["mobile_sms_id"=>$result['mobile_sms_id']])->update(["state"=>2]);
                if($log && $lag){
                    $gwd = $lag.','.$log;
                    $baidu_apikey =DB::name('system')->where("")->value('baidu_apikey');
                    $file_contents = file_get_contents('http://api.map.baidu.com/geocoder/v2/?ak='.$baidu_apikey.'&location='.$gwd.'&output=json');
                    $rs = json_decode($file_contents,true);
                    DB::name("Login_hostroy")->add(['user_id'=>$user['member_id'],'log'=>$log,'lag'=>$lag,'area'=>$rs['result']['addressComponent']['city'],'address'=>$rs['result']['formatted_address'],'intime'=>time(),'date'=>date('Y-m-d',time())]);
                }
                success($user);
            }
        }else{
            //用户不存在的时候
            $photo =  $photo = "/Public/admin/touxiang.png";
            $chars = "abcdefghijklmnopqrstuvwxyz123456789";
            mt_srand(10000000*(double)microtime());
            for ($i = 0, $str = '', $lc = strlen($chars)-1; $i < 12; $i++){
                $str .= $chars[mt_rand(0, $lc)];
            }
            $photo = "/Public/admin/touxiang.png";
            $hx_password="123456";
            $date = [
                'member_token'=>uniqid(),
                'member_phone'=>$mobile,
                'member_head_image'=>$photo,
                'member_nick_name'=>"游荡者",
                'ID'=>get_number(),
                'create_time'=>time(),
                'member_alias'=>$str,
                'personalized_signature'=>"这个人很懒什么都没有留下！！",
                'hx_username'=>$str,
                'member_sex'=>1,
                'hx_password'=>$hx_password,
            ];
            if ($member_id=DB::name('member')->insert($date)){
                //验证成功进行状态修改
                DB::name("mobile_sms")->where(["mobile_sms_id"=>$result['mobile_sms_id']])->update(["state"=>2]);
                $hx = new Easemob();
                $result = $hx->huanxin_zhuce($str,$hx_password); //环信注册
                if(!$result){
                    error("授权注册失败");
                }
                $user = DB::name('member')->where(['member_id'=>$member_id])->find();
                $user['img'] = C('IMG_PREFIX').$user['img'];
                success($user);
            }else {
                error('失败!');
            }
        }
    }

}
