<?php
namespace app\api\controller;
use think\Controller;
use think\Db;
use think\Request;
class User extends Common{
    public function  _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 获取用户信息
     */
    public function user_info(){
        //待优化
        $user = $this->checklogin();
        $user['header_img'] = $user['header_img'];
        $user['follow'] = DB::name('Follow')->where(['user_id'=>$user['member_id']])->count();
        $user['follow_to'] = DB::name('Follow')->where(['user_id2'=>$user['member_id']])->count();
        $user['live_count'] = DB::name('Live_store')->where(['user_id'=>$user['member_id'],'is_del'=>1])->count();
        $give_count = DB::name('Give_gift')->where(['user_id'=>$user['member_id']])->sum('jewel');
        $give_count ? $user['give_count'] = $give_count : $user['give_count'] = "0";
//        $authen = M('User_authen')->where(['user_id'=>$user['user_id']])->find();
//        if ($authen){
//            $user['is_authen'] = $authen['status'];
//        }else{
//            $user['is_authen'] = "-1";
//        }
        success($user);
    }
    /**
     * @编辑个人资料
     */
    public function edit_user(){
        $user = $this->checklogin();
        $params = Request::instance()->request();
        empty($params["header_img"]) ?  true : $data["header_img"] = $params["header_img"];
        empty($params["username"]) ?  true :  $data["username"] = $params["username"];
        empty($params["sex"]) ?  true :$data["sex"] = $params["sex"];
        empty($params["birth_day"]) ?  true :$data["birth_day"] =  $params["birth_day"];
        empty($params["province"]) ?  true : $data["province"] = $params["province"];
        empty($params["city"]) ?  true : $data["city"] = $params["city"];
        empty($params["area"]) ?  true : $data["area"] = $params["area"];

        if (!empty($username)){
            $user = DB::name('member')->where(['username'=>$username])->find();
            if ($user){error('昵称已存在!');}
        }
        //待处理
        $data['uptime'] = time();
        $old_img = DB::name('member')->where(['member_id'=>$user['member_id']])->value('header_img');
        if(DB::name('member')->where(['member_id'=>$user['member_id']])->update($data)){
           //bug(旧文件的删除
            $imgs = DB::name('member')->where(['member_id'=>$user['member_id']])->value('header_img');
            success($imgs);
        }else{
            error('失败!');
        }
    }

}