<?php
namespace app\api\controller;
use think\Controller;
use think\Db;
class User extends Common{
    public function  _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 获取用户相管信息
     */
    public function user_info(){
        //待优化
        $user = $this->checklogin();
        $user['header_img'] = $user['header_img'];
        $user['follow'] = DB::name('Follow')->where(['user_id'=>$user['member_id']])->count();
        $user['follow_to'] = DB::name('Follow')->where(['user_id2'=>$user['member_id']])->count();
        $user['live_count'] = DB::name('Live_store')->where(['user_id'=>$user['member_id'],'is_del'=>1])->count();
        $give_count = DB::name('Give_gift')->where(['user_id'=>$user['member_id']])->sum('jewel');
        $give_count ? $user['give_count'] = $give_count : $user['give_count'] = "0";
//        $authen = M('User_authen')->where(['user_id'=>$user['user_id']])->find();
//        if ($authen){
//            $user['is_authen'] = $authen['status'];
//        }else{
//            $user['is_authen'] = "-1";
//        }
        success($user);
    }
    /**
     * @编辑个人资料
     */
    public function edit_user(){
        $user = checklogin();
        $params = Request::instance()->request();
        $header_img = empty($params["header_img"]) ?  true : $params["header_img"];
        $username = empty($params["username"]) ?  true : $params["username"];
        $sex = empty($params["sex"]) ?  true : $params["sex"];
        $birth_day = empty($params["birth_day"]) ?  true : $params["birth_day"];
        $province = empty($params["province"]) ?  true : $params["province"];
        $city = empty($params["city"]) ?  true : $params["city"];
        $area = empty($params["area"]) ?  true : $params["area"];

        if (!empty($username)){
            $user = DB::name('member')->where(['username'=>$username])->find();
            if ($user){error('昵称已存在!');}
        }
        //待处理
        $data['uptime'] = time();
        $old_img = M('member')->where(['user_id'=>$user['member_id']])->getField('img');
        if(M('User')->where(['user_id'=>$user['user_id']])->save($data)){
            if ($a!=$old_img){
                unlink($old_img);
            }
            $imgs = C('IMG_PREFIX').M('User')->where(['user_id'=>$user['user_id']])->getField('img');
            success($imgs);
        }else{
            error('失败!');
        }
    }

}